#ifndef UNISEEK_CONFIG_H
#define UNISEEK_CONFIG_H

#define UNISEEK_WIFI_SSID "YOUR_WIFI_SSID"
#define UNISEEK_WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#define UNISEEK_SERVER_IP "192.168.1.100"
#define UNISEEK_SERVER_PORT 8080
#define UNISEEK_API_PATH "/api/v1/telemetry"
#define UNISEEK_SAMPLE_INTERVAL_MS 10000
#define UNISEEK_HTTP_RETRY_COUNT 3
#define UNISEEK_HTTP_RETRY_INTERVAL_MS 2000
#define UNISEEK_WIFI_RECONNECT_INTERVAL_MS 5000
#define UNISEEK_DISPLAY_INTERVAL_MS 500
#define UNISEEK_HTTP_TIMEOUT_MS 5000

#endif
